spring:
  application:
    name: fastfood-order

  data:
    mongodb:
      repositories: true
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true
      uuid-representation: standard
      host: ${MONGODB_HOST:localhost}
      authentication-database: admin
      database: ${MONGODB_DATABASE:fastfood}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}


payment:
  sqs:
    queue: ${PAYMENT_QUEUE_NAME:fastfood-payment-queue}
  webhook: ${WEBHOOK_URL:http://fastfood-order:8080/v1/payment/receive}
  client:
    connectionTimeout: 50000
    responseTimeout: 50000
    readTimeout: 50000
    writeTimeout: 50000
    maxConnections: 5
    url: ${PAYMENT_URL:http://fastfood-payment-mock:8084}

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"