spring:
  application:
    name: fastfood-order

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      repositories: true
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true
      uuid-representation: standard
      host: ${MONGODB_HOST:localhost}
      authentication-database: admin
      database: ${MONGODB_DATABASE:fastfood}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}

aws:
  sqs:
    numberOfMessages: 5
    waitTimeMessage: 10
    numberOfRetries: 10
    visibilityTimeOut: 30
    tracking:
      queue: ${TRACKING_QUEUE_NAME:tracking_queue}
    order:
      queue: ${ORDER_QUEUE_NAME:order_queue}
    payment:
      queue: ${PAYMENT_QUEUE_NAME:payment_queue}
    customer:
      queue: ${CUSTOMER_QUEUE_NAME:customer_queue}

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"